/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface AnProgressBar {
    'theme': string;
    'value': number;
  }
  interface AnProgressBarAttributes extends StencilHTMLAttributes {
    'theme'?: string;
    'value'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AnProgressBar': Components.AnProgressBar;
  }

  interface StencilIntrinsicElements {
    'an-progress-bar': Components.AnProgressBarAttributes;
  }


  interface HTMLAnProgressBarElement extends Components.AnProgressBar, HTMLStencilElement {}
  var HTMLAnProgressBarElement: {
    prototype: HTMLAnProgressBarElement;
    new (): HTMLAnProgressBarElement;
  };

  interface HTMLElementTagNameMap {
    'an-progress-bar': HTMLAnProgressBarElement
  }

  interface ElementTagNameMap {
    'an-progress-bar': HTMLAnProgressBarElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
